### ISSUE TITLE
App crash when I enable the GPIO option

### ISSUE THREAD

**Issue by mgrl** [mgrl/photobooth-app#110]
### Discussed in https://github.com/mgrl/photobooth-app/discussions/109

<div type='discussions-op-text'>

<sup>Originally posted by **laguinch** October 27, 2023</sup>
hy, the app crash when I enable the gpio option on my bulleye and rpi4 installation

 photobooth
added provider for picamera2 backend
added provider for gphoto2 backend
added provider for webcamv4l backend
2023-10-27 11:56:44,172 [   DEBUG] loggingservice __init__ basicConfig set (loggingservice.py:95)
2023-10-27 11:56:44,172 [   DEBUG] loggingservice __init__ started (loggingservice.py:96)
2023-10-27 11:56:44,173 [   DEBUG] loggingservice __init__ finished (loggingservice.py:130)
2023-10-27 11:56:44,176 [   DEBUG] registered handlers: [<StreamHandler <stderr> (NOTSET)>, <FileHandler /home/pi/log/photobooth_20231027.log (NOTSET)>, <EventstreamLogHandler (NOTSET)>] (loggingservice.py:131)
2023-10-27 11:56:44,579 [    INFO] photobooth directory: /home/pi/.local/lib/python3.9/site-packages/photobooth (__main__.py:81)
2023-10-27 11:56:44,580 [    INFO] working directory: /home/pi (__main__.py:83)
2023-10-27 11:56:44,581 [    INFO] app version started: 0.11.0 (__main__.py:84)
2023-10-27 11:56:44,671 [    INFO] loading autofocus module: picamera2_LibcamAfContinuous (picamera2_.py:94)
2023-10-27 11:56:44,671 [    INFO] photobooth.services.backends.picamera2_libcamafcontinuous initialized (picamera2_libcamafcontinuous.py:41)
[0:04:38.596498746] [4858]  INFO Camera camera_manager.cpp:297 libcamera v0.0.0+4367-ad9428b4
[0:04:38.648052011] [4865]  INFO RPI vc4.cpp:444 Registered camera /base/soc/i2c0mux/i2c@1/imx519@1a to Unicam device /dev/media4 and ISP device /dev/media0
[0:04:38.648136341] [4865]  INFO RPI pipeline_base.cpp:1101 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'
2023-10-27 11:56:44,727 [    INFO] Initialization successful. (picamera2.py:428)
2023-10-27 11:56:44,727 [    INFO] Camera now open. (picamera2.py:449)
2023-10-27 11:56:44,732 [   DEBUG] change to preview mode requested (picamera2_.py:309)
2023-10-27 11:56:44,734 [    INFO] Camera configuration has been adjusted! (picamera2.py:940)
[0:04:38.658986887] [4858]  INFO Camera camera.cpp:1033 configuring streams: (0) 2328x1748-XBGR8888 (1) 1280x720-YUV420 (2) 2328x1748-SBGGR10_CSI2P
[0:04:38.659698142] [4865]  INFO RPI vc4.cpp:572 Sensor: /base/soc/i2c0mux/i2c@1/imx519@1a - Selected sensor format: 2328x1748-SBGGR10_1X10 - Selected unicam format: 2328x1748-pBAA
2023-10-27 11:56:44,737 [    INFO] Configuration successful! (picamera2.py:945)
2023-10-27 11:56:44,768 [    INFO] camera_config: {'use_case': 'video', 'transform': <libcamera.Transform 'hvflip'>, 'colour_space': <libcamera.ColorSpace 'Rec709'>, 'buffer_count': 2, 'queue': True, 'main': {'format': 'XBGR8888', 'size': (2328, 1748), 'stride': 9344, 'framesize': 16333312}, 'lores': {'format': 'YUV420', 'size': (1280, 720), 'stride': 1280, 'framesize': 1382400}, 'raw': {'format': 'SBGGR10_CSI2P', 'size': (2328, 1748), 'stride': 2912, 'framesize': 5090176}, 'controls': {'NoiseReductionMode': <NoiseReductionModeEnum.Fast: 1>, 'FrameDurationLimits': (33333, 33333)}, 'display': 'lores', 'encode': 'lores'} (picamera2_.py:173)
2023-10-27 11:56:44,769 [    INFO] camera_controls: {'ColourGains': (0.0, 32.0, None), 'AfMetering': (0, 1, 0), 'AnalogueGain': (1.0, 16.0, None), 'Saturation': (0.0, 32.0, 1.0), 'Contrast': (0.0, 32.0, 1.0), 'AeMeteringMode': (0, 3, 0), 'AfMode': (0, 2, 0), 'AeConstraintMode': (0, 3, 0), 'AeEnable': (False, True, None), 'ExposureTime': (305, 0, None), 'AfPause': (0, 2, 0), 'AfRange': (0, 2, 0), 'NoiseReductionMode': (0, 4, 0), 'ScalerCrop': ((0, 0, 128, 128), (0, 0, 4656, 3496), (0, 0, 4656, 3496)), 'Sharpness': (0.0, 16.0, 1.0), 'AwbEnable': (False, True, None), 'FrameDurationLimits': (33333, 127960799, None), 'ExposureValue': (-8.0, 8.0, 0.0), 'AwbMode': (0, 7, 0), 'AeExposureMode': (0, 3, 0), 'AfSpeed': (0, 1, 0), 'AfTrigger': (0, 1, 0), 'AfWindows': ((0, 0, 0, 0), (65535, 65535, 65535, 65535), (0, 0, 0, 0)), 'Brightness': (-1.0, 1.0, 0.0), 'LensPosition': (0.0, 32.0, 1.0)} (picamera2_.py:174)
2023-10-27 11:56:44,769 [    INFO] controls: <Controls: {'NoiseReductionMode': <NoiseReductionModeEnum.Fast: 1>, 'FrameDurationLimits': (33333, 33333)}> (picamera2_.py:175)
2023-10-27 11:56:44,770 [    INFO] set_ae_exposure, try to set to 1 (picamera2_.py:319)
2023-10-27 11:56:44,771 [    INFO] current picamera2.controls.get_libcamera_controls():{libcamera.ControlId(39, NoiseReductionMode, ControlType.Integer32): <NoiseReductionModeEnum.Fast: 1>, libcamera.ControlId(25, FrameDurationLimits, ControlType.Integer64): (33333, 33333), libcamera.ControlId(5, AeExposureMode, ControlType.Integer32): 1} (picamera2_.py:326)
2023-10-27 11:56:44,771 [    INFO] stream quality Quality[self._config.backends.picamera2_stream_quality.name]=<Quality.MEDIUM: 2> (picamera2_.py:178)
2023-10-27 11:56:44,983 [    INFO] Camera started (picamera2.py:1026)
2023-10-27 11:56:44,985 [    INFO] photobooth.services.backends.picamera2_libcamafcontinuous _init_autofocus call (picamera2_libcamafcontinuous.py:72)
2023-10-27 11:56:44,986 [    INFO] libcamautofocus set to continuous mode (picamera2_libcamafcontinuous.py:75)
2023-10-27 11:56:44,986 [    INFO] libcamautofocus AfSpeed set to fast mode (picamera2_libcamafcontinuous.py:81)
2023-10-27 11:56:45,263 [   DEBUG] photobooth.services.backends.picamera2_ started (picamera2_.py:209)
2023-10-27 11:56:45,264 [    INFO] init self.primary_backend=<class 'photobooth.services.backends.picamera2_.Picamera2Backend'> (aquisitionservice.py:39)
2023-10-27 11:56:45,264 [    INFO] init self.secondary_backend=None (aquisitionservice.py:40)
2023-10-27 11:56:45,269 [    INFO] init database and creating missing scaled images. this might take some time. (mediacollectionservice.py:58)
2023-10-27 11:56:45,278 [    INFO] initialized image DB, added 1 valid images (mediacollectionservice.py:75)
2023-10-27 11:56:45,279 [    INFO] -- process time: 0.01s to initialize mediacollection (mediacollectionservice.py:76)
2023-10-27 11:56:45,286 [    INFO] on_enter_state self.current_state.id='idle'  (processingservice.py:91)
2023-10-27 11:56:45,287 [    INFO] state idle entered. (processingservice.py:105)
2023-10-27 11:56:45,304 [   ERROR] Uncaught exception: <class 'RuntimeError'> Not running on a RPi! (loggingservice.py:195)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 101, in pin
    pin = self.pins[n]
KeyError: 17

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/bin/photobooth", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/photobooth/__main__.py", line 91, in main
    application_container.services().gpio_service.init()
  File "src/dependency_injector/providers.pyx", line 3786, in dependency_injector.providers.Resource.init
  File "src/dependency_injector/providers.pyx", line 225, in dependency_injector.providers.Provider.__call__
  File "src/dependency_injector/providers.pyx", line 3865, in dependency_injector.providers.Resource._provide
  File "/home/pi/.local/lib/python3.9/site-packages/photobooth/services/containers.py", line 67, in init_gpio_resource
    resource = GpioService(
  File "/home/pi/.local/lib/python3.9/site-packages/photobooth/services/gpioservice.py", line 54, in __init__
    self.init_io()
  File "/home/pi/.local/lib/python3.9/site-packages/photobooth/services/gpioservice.py", line 63, in init_io
    self.shutdown_btn = Button(
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 108, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/input_devices.py", line 414, in __init__
    super(Button, self).__init__(
  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 433, in __init__
    super(HoldMixin, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/input_devices.py", line 165, in __init__
    super(DigitalInputDevice, self).__init__(
  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 218, in __init__
    super(EventsMixin, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/input_devices.py", line 83, in __init__
    super(InputDevice, self).__init__(pin, pin_factory=pin_factory)
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 549, in __init__
    pin = self.pin_factory.pin(pin)
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 103, in pin
    pin = self.pin_class(self, n)
  File "/usr/lib/python3/dist-packages/gpiozero/pins/rpigpio.py", line 111, in __init__
    GPIO.setup(self.number, GPIO.IN, self.GPIO_PULL_UPS[self._pull])
RuntimeError: Not running on a RPi!
</div>

**Comment by mgrl** [comment]
This could be an issue with the latest gpiozero library. I will check later the weekend.

**Comment by mgrl** [comment]
Installation on Pi was probably off - tested on fresh system, works fine.
But services need to be improved so one service cannot crash the whole app.
